language: go
sudo: required

go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - master

before_install:
  - curl https://glide.sh/get | sh

install:
  - glide install

script:
  - go test -v $(glide novendor)
  - go build
