language: go
sudo: required

go:
  - 1.8.x
  - master

before_install:
  - curl https://glide.sh/get | sh

install:
  - glide install

jobs:
  include:
    - stage: test
      script: go test -v $(glide novendor)
    - stage: build
      script: go build