language: go
sudo: required

go:
  - 1.x
  - 1.6
  - 1.7.x
  - master

before_install:
  - curl https://glide.sh/get | sh

install:
  - glide install

jobs:
  include:
    - stage: test
      script: go test -v ./...
    - stage: build
      script: go build