language: go
sudo: required

go:
  - 1.7
  - 1.8
  - master

before_install:
  - curl https://glide.sh/get | sh

install:
  - glide install

script:
  - go test -v $(glide novendor)
  - go build

#jobs:
#  include:
#    - stage: test
#      script: go test -v $(glide novendor)
#    - stage: build
#      script: go build